### ISSUE TITLE
Figure Rendering Issue in R 

### ISSUE THREAD

**Issue by emmaclinton** [GIS4DEV/RP-Malcomb#2]
Hi! This code was working earlier: 

```
{r 2010 adaptive capacity map}
map_2010 = ggplot() +
  geom_sf(data = ea,
          aes(fill = EA),
          color = NA) +
  geom_sf(
    data = ta_2010,
    aes(fill = capacity_2010_brks),
    color = "white",
    lwd = .2
  ) + scale_fill_manual(
    values = list(
      "Missing Data" = "#FFC389",
      "National Parks and Reserves" = "#D9EABB",
      "Major Lakes of Malawi" = "lightblue",
      "13.95 - 15.84" = "#333333",
      "15.84 - 17.13" = "#666666",
      "17.13 - 18.89" = "#999999",
      "18.89 - 21.36" = "#CCCCCC"
    )
  ) +
  scale_x_continuous(breaks = c(33,34,35,36)) +
  labs(title = "Adaptive Capacity Scores Based on 2010 DHS Surveys in 222 Traditional Authorities") +
  theme_minimal() +
  theme(legend.title = element_blank())
map_2010
```

but now I'm running into the error: 'Error: Unknown color name: NULL"

Does anyone know what might be going on?

**Comment by josephholler** [comment]
This looks identical to the original code for the 2010 map, right?  I don't see a problem.
I'm wondering though if all the libraries are loaded and all of the necessary data objects, e.g. `ea` and `capacity_2010_brks` have been created in your current R environment?

**Comment by emmaclinton** [comment]
Yes, that's why I'm so confused...the ta_2010 data has a capacity_2010_brks field with valid data and ea definitely exists and has "National Parks and Reserves" row entries, so everything else seems to be working.

**Comment by emmaclinton** [comment]
Oh wait a sec. New data break values.
